### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [1]:
!pip install tensorflow-gpu

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'


Requested tensorflow-gpu from https://files.pythonhosted.org/packages/8a/45/fa31ced1db38f9424f262dfbf35747fe5378b5c808cecb373c8cb8e515d3/tensorflow-gpu-2.12.0.tar.gz has invalid metadata: Expected end or semicolon (after name and no valid version specifier)
    python_version>"3.7"
                  ^
Please use pip<24.1 if you need to use this version.
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu (from versions: 2.12.0)
ERROR: No matching distribution found for tensorflow-gpu


In [2]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [3]:
# import tensorflow as tf
# print(tf.__version__)

In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [25]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [26]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[458, 360, 338, 54, 245, 303], [98, 168, 338, 357, 355, 469], [10, 31, 242, 51], [458, 446, 338, 450, 458, 149], [423, 435, 20, 338, 357, 355, 469], [6, 338, 357, 355, 164, 399]]


### Word Embedding Represntation

In [27]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [28]:
import numpy as np

In [52]:
## pre padding
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print("Padded sequences:","\n", embedded_docs)


Padded sequences: 
 [[  0   0 458 360 338  54 245 303]
 [  0   0  98 168 338 357 355 469]
 [  0   0   0   0  10  31 242  51]
 [  0   0 458 446 338 450 458 149]
 [  0 423 435  20 338 357 355 469]
 [  0   0   6 338 357 355 164 399]]


In [53]:
## 10 feature dimesnions
dim=10


In [54]:
# model=Sequential()
# model.add(Embedding(voc_size,10,input_length=sent_length))
# model.compile('adam','mse')


model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam', 'mse')


In [55]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0, 458, 360, 338,  54, 245, 303])

In [56]:
# CORRECT WAY: Add batch dimension for single prediction
single_sample = embedded_docs[0].reshape(1, -1)  # Shape: (1, 8)
print("Single sample shape:", single_sample.shape)


Single sample shape: (1, 8)


In [35]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step


array([[-0.01310626,  0.00112356,  0.02377781,  0.01835423, -0.02412928,
        -0.04036956, -0.04549645, -0.03398637, -0.02234002,  0.03050264],
       [-0.01310626,  0.00112356,  0.02377781,  0.01835423, -0.02412928,
        -0.04036956, -0.04549645, -0.03398637, -0.02234002,  0.03050264],
       [-0.03539174, -0.03546584, -0.02298042,  0.00572394,  0.02818516,
         0.0362691 , -0.02483915,  0.00557212, -0.01839165,  0.02268657],
       [ 0.00801327, -0.02959882, -0.00126355, -0.00504006, -0.02814428,
         0.04356656, -0.04333502, -0.02882379, -0.00871437, -0.03938683],
       [ 0.01949682, -0.049915  ,  0.00545994,  0.00012542, -0.02550679,
        -0.04599611,  0.00334512,  0.03382013,  0.03352425,  0.01729084],
       [-0.02778885,  0.00206101,  0.04160004,  0.0280761 , -0.03017658,
        -0.00856685,  0.03726175,  0.00549666, -0.03277516, -0.00469974],
       [-0.04855328, -0.0160246 , -0.02803394,  0.03831531, -0.03974699,
         0.01130637,  0.03857276, -0.03942158

In [57]:
# Now this will work
prediction = model.predict(single_sample)
print("Prediction shape:", prediction.shape)
print("Prediction for first sample:")
print(prediction)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
Prediction shape: (1, 8, 10)
Prediction for first sample:
[[[ 0.01508826  0.03731165 -0.04477267 -0.01881378  0.04880742
    0.04189129 -0.03565949 -0.01232551 -0.01511848 -0.00221969]
  [ 0.01508826  0.03731165 -0.04477267 -0.01881378  0.04880742
    0.04189129 -0.03565949 -0.01232551 -0.01511848 -0.00221969]
  [ 0.00978243  0.02949638 -0.0199896   0.03381722  0.02637557
    0.01027501  0.01207916  0.0152829  -0.02399039 -0.02040409]
  [ 0.01330098  0.03715081  0.02100633  0.00363296 -0.00978042
   -0.04836234  0.04038901  0.00166911 -0.01863459 -0.04220449]
  [-0.02104272  0.0396758   0.02926676  0.03346052  0.03258163
   -0.03206806 -0.0259099   0.04748947 -0.01630469 -0.0292694 ]
  [-0.00746778 -0.02175212  0.0232533  -0.02881334 -0.03659592
    0.01944995  0.04931939  0.0374716  -0.00831848 -0.04148237]
  [ 0.03969212  0.03723086  0.02446962  0.02325666  0.01515193
    0.02263964  0.03549604 -0.01114868 -0.02780709  0.03493563]
  [ 0.02893348

In [58]:
# Predict on all samples (already has correct shape: (7, 8))
all_predictions = model.predict(embedded_docs)
print("\nAll predictions shape:", all_predictions.shape)
print("All predictions:")
print(all_predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

All predictions shape: (6, 8, 10)
All predictions:
[[[ 0.01508826  0.03731165 -0.04477267 -0.01881378  0.04880742
    0.04189129 -0.03565949 -0.01232551 -0.01511848 -0.00221969]
  [ 0.01508826  0.03731165 -0.04477267 -0.01881378  0.04880742
    0.04189129 -0.03565949 -0.01232551 -0.01511848 -0.00221969]
  [ 0.00978243  0.02949638 -0.0199896   0.03381722  0.02637557
    0.01027501  0.01207916  0.0152829  -0.02399039 -0.02040409]
  [ 0.01330098  0.03715081  0.02100633  0.00363296 -0.00978042
   -0.04836234  0.04038901  0.00166911 -0.01863459 -0.04220449]
  [-0.02104272  0.0396758   0.02926676  0.03346052  0.03258163
   -0.03206806 -0.0259099   0.04748947 -0.01630469 -0.0292694 ]
  [-0.00746778 -0.02175212  0.0232533  -0.02881334 -0.03659592
    0.01944995  0.04931939  0.0374716  -0.00831848 -0.04148237]
  [ 0.03969212  0.03723086  0.02446962  0.02325666  0.01515193
    0.02263964  0.03549604 -0.01114868 -0.02780709  0.03493563]
  [ 0.02893348 -0.032

In [59]:
# model.predict(embedded_docs)

In [60]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

max_length = 10  # must match training
padded_docs = pad_sequences(embedded_docs, maxlen=max_length, padding='post')
padded_docs = np.array(padded_docs)

preds = model.predict(padded_docs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


In [37]:
embedded_docs[0]

array([  0,   0, 458, 360, 338,  54, 245, 303])

In [61]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[ 0.01508826  0.03731165 -0.04477267 -0.01881378  0.04880742  0.04189129
  -0.03565949 -0.01232551 -0.01511848 -0.00221969]
 [ 0.01508826  0.03731165 -0.04477267 -0.01881378  0.04880742  0.04189129
  -0.03565949 -0.01232551 -0.01511848 -0.00221969]
 [ 0.00978243  0.02949638 -0.0199896   0.03381722  0.02637557  0.01027501
   0.01207916  0.0152829  -0.02399039 -0.02040409]
 [ 0.01330098  0.03715081  0.02100633  0.00363296 -0.00978042 -0.04836234
   0.04038901  0.00166911 -0.01863459 -0.04220449]
 [-0.02104272  0.0396758   0.02926676  0.03346052  0.03258163 -0.03206806
  -0.0259099   0.04748947 -0.01630469 -0.0292694 ]
 [-0.00746778 -0.02175212  0.0232533  -0.02881334 -0.03659592  0.01944995
   0.04931939  0.0374716  -0.00831848 -0.04148237]
 [ 0.03969212  0.03723086  0.02446962  0.02325666  0.01515193  0.02263964
   0.03549604 -0.01114868 -0.02780709  0.03493563]
 [ 0.02893348 -0.03254499 -0.00099887  0.02498475 -0.03745548 -0.01478788
  -0.03390563

In [62]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]