Corpus - Word Combination


Vokabulary :- unik word  in Corpus

Document:- Individual review

Word :- In the Docoment Individual Words such as One document is know as  World

In [5]:
import numpy as np
import pandas as pd

<h1>Bag of Words</h1>
<p>Bag of Words (BoW) is a simple and commonly used method for text representation

In [6]:
df = pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0, 0]})
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer()

In [8]:
bow=cv.fit_transform(df['text'])
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

In [9]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [10]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [11]:
cv.transform(["campusx watch and write comment of campusx"]). toarray()

array([[2, 1, 0, 1, 1]])

<h1>N grams</h1>

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

# cv=CountVectorizer(ngram_range=(2,2))
# cv=CountVectorizer(ngram_range=(1,2))
cv=CountVectorizer(ngram_range=(1,3))



In [13]:
bow=cv.fit_transform(df['text'])

In [14]:
print(cv.vocabulary_)

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}


In [15]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 0 0 0 0 1 1 1 0 0 1 1 0 0]]
[[2 1 1 0 0 0 0 0 0 0 0 1 1 0 0]]


In [16]:
cv.transform(["campusx watch and write comment of campusx"]). toarray()

array([[2, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1]])

<h1>Tf-Idf</h1>

TF-IDF, which stands for Term Frequency-Inverse Document Frequency, is a numerical statistic that reflects the importance of a word to a document in a collection or corpus. It's a widely used technique in natural language processing (NLP) and information retrieval to assess how relevant a word is within a document compared to its frequency across the entire collection.

<br>
1. Term Frequency (TF):-<br>
Measures how often a term (word) appears in a specific document.
A higher frequency suggests the term is more relevant to that document.
For example, if the word "algorithm" appears 10 times in a document and 50 times in another, it's likely more relevant to the first document. <br> <br> <br>
2. Inverse Document Frequency (IDF):-<br>
Measures how common or rare a term is across the entire collection of documents (corpus). 
Common words across many documents get a low IDF score, while rare words get a high score. 
This is because rare words are more likely to be specific to a document. 
For instance, the word "the" appears in almost every document, so its IDF score will be low. The word "quantum," on the other hand, might appear in only a few documents, giving it a higher IDF score. 

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer    

tfidf=TfidfVectorizer()

tfidf_bow=tfidf.fit_transform(df['text']).toarray()

tfidf_bow

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [18]:
print(tfidf.idf_)

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]


In [19]:
print(tfidf.get_feature_names_out())

['campusx' 'comment' 'people' 'watch' 'write']
