In [17]:
import pandas as pd

In [18]:
a=pd.read_csv(r"D:\CODING\PYTHON\NLP\IMDB Dataset_1.csv")
a

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [19]:
a=a.iloc[:10000]

In [20]:
a.duplicated().sum()

np.int64(17)

In [21]:
a.drop_duplicates(inplace=True)

C:\Users\sinha\AppData\Local\Temp\ipykernel_8784\898602298.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a.drop_duplicates(inplace=True)


In [22]:
a

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. <br /><br />The...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [23]:
a["sentiment"].value_counts()

sentiment
positive    5023
negative    4960
Name: count, dtype: int64

In [24]:
a["review"]=a["review"].str.lower()

C:\Users\sinha\AppData\Local\Temp\ipykernel_8784\669757413.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["review"]=a["review"].str.lower()


In [25]:
import re
def remove_html(text):
    p=re.compile("<.*?>")
    return p.sub(r'',text)

In [26]:
a["review"]=a["review"].apply(remove_html)

C:\Users\sinha\AppData\Local\Temp\ipykernel_8784\1004165951.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["review"]=a["review"].apply(remove_html)


In [27]:
def remove_url(text):
    p=re.compile(r'http?//\S+|www\.S+')
    return p.sub(r'',text)

In [28]:
a["review"]=a["review"].apply(remove_html)

C:\Users\sinha\AppData\Local\Temp\ipykernel_8784\1004165951.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["review"]=a["review"].apply(remove_html)


In [29]:
import string
pu=string.punctuation

def remove_punction(text):
    return text.translate(str.maketrans('','',pu))

In [30]:
a["review"]=a["review"].apply(remove_punction)

C:\Users\sinha\AppData\Local\Temp\ipykernel_8784\1955178318.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["review"]=a["review"].apply(remove_punction)


In [31]:
from nltk.corpus import stopwords

def remove_stopword(text):
    new_text=[]
    for i in text.split():
        if i in stopwords.words("english"):
            new_text.append('')
        else:
            new_text.append(i)
    x=new_text[ : ]
    new_text.clear()
    return " ".join(x)


In [33]:
a["review"]=a["review"].apply(remove_stopword)

KeyboardInterrupt: 

In [17]:
a

review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production the filming tech...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically theres a family where a little boy j...  negative
4     petter matteis love in the time of money is a ...  positive
...                                                 ...       ...
9995  fun entertaining movie about wwii german spy j...  positive
9996  give me a break how can anyone say that this i...  negative
9997  this movie is a bad movie but after watching a...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about filmmaking shows the inten...  positive

[9983 rows x 2 columns]

In [18]:
x=a.iloc[:,0:1]
y=a.iloc[:,-1]

In [19]:
x

review
0     one of the other reviewers has mentioned that ...
1     a wonderful little production the filming tech...
2     i thought this was a wonderful way to spend ti...
3     basically theres a family where a little boy j...
4     petter matteis love in the time of money is a ...
...                                                 ...
9995  fun entertaining movie about wwii german spy j...
9996  give me a break how can anyone say that this i...
9997  this movie is a bad movie but after watching a...
9998  this is a movie that was probably made to ente...
9999  smashing film about filmmaking shows the inten...

[9983 rows x 1 columns]

In [20]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [21]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
y=le.fit_transform(y)


In [22]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [23]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.2)

In [24]:
x_train

review
6713  ive been waiting for a superhero movie like th...
1178  this movie was an excellent acted excellent di...
4707  this movie makes me want to throw up every tim...
6772  i first saw this movie when i was in elementar...
7461  this show is made for persons with iq lower th...
...                                                 ...
2895  excellent episode movie ala pulp fiction 7 day...
7823  first off to give you some idea of my taste in...
905   well where do i begin my story i went to this ...
5195  a lot of horror fans seem to love scarecrows s...
235   reese witherspoon first outing on the big scre...

[7986 rows x 1 columns]

In [25]:
y_test

array([1, 1, 0, ..., 1, 0, 0])

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer()
x_train_bow=cv.fit_transform(x_train["review"]).toarray()
x_test_bow=cv.transform(x_test["review"]).toarray()

In [27]:
from sklearn.naive_bayes import GaussianNB

gn=GaussianNB()
gn.fit(x_train_bow,y_train)

GaussianNB()

In [28]:
from sklearn.metrics import accuracy_score,confusion_matrix

y_pred=gn.predict(x_test_bow)

accuracy_score(y_test,y_pred)*100


65.99899849774661

In [31]:
gn.score(x_test_bow,y_test)*100

65.99899849774661

In [29]:
confusion_matrix(y_test,y_pred)

array([[693, 259],
       [420, 625]], dtype=int64)

In [33]:
from sklearn.linear_model import LogisticRegression
lor=LogisticRegression()

lor.fit(x_train_bow,y_train)
lor.score(x_test_bow,y_test)*100


c:\Users\sinha\anaconda3\envs\ENV1\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


87.33099649474211

In [39]:
import pandas as pd 
a=pd.read_csv(r"D:\CODING\PYTHON\NLP\spam.csv",encoding='cp1252')
a

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [41]:
a.duplicated().sum()

403

In [42]:
a.drop_duplicates(inplace=True)

In [43]:
a.duplicated().sum()

0

In [44]:
a

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5169 rows x 5 columns]

In [46]:
a["v2"]=a["v2"].str.lower()

In [47]:
a["v2"]

0       go until jurong point, crazy.. available only ...
1                           ok lar... joking wif u oni...
2       free entry in 2 a wkly comp to win fa cup fina...
3       u dun say so early hor... u c already then say...
4       nah i don't think he goes to usf, he lives aro...
                              ...                        
5567    this is the 2nd time we have tried 2 contact u...
5568                will ì_ b going to esplanade fr home?
5569    pity, * was in mood for that. so...any other s...
5570    the guy did some bitching but i acted like i'd...
5571                           rofl. its true to its name
Name: v2, Length: 5169, dtype: object

In [48]:
import re
def remove_html(text):
    p=re.compile("<.*?/>")
    return p.sub(r'',text)


In [49]:
a["v2"]=a["v2"].apply(remove_html)

In [ ]:
def remove_url(text):
    p=re.compile(r'http')

In [50]:
import string
pu=string.punctuation

def remove_punction(text):
    return text.translate(str.maketrans('','',pu))

In [51]:
a["v2"]=a["v2"].apply(remove_punction)

In [52]:
from nltk.corpus import stopwords

def remove_stopword(text):
    new_text=[]
    for i in text.split():
        if i in stopwords.words("english"):
            new_text.append('')
        else:
            new_text.append(i)
    x=new_text[ : ]
    new_text.clear()
    return " ".join(x)

In [53]:
a["v2"]=a["v2"].apply(remove_punction)